name: Release Pages

on:
  # 手动触发
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  aurora:
    runs-on: ubuntu-latest
    if: ${{ vars.THEME == 'aurora' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          path: hexo-blog

      - uses: actions/checkout@v4
        with:
          ref: aurora-theme
          fetch-depth: 0
          path: hexo-blog-aurora

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: 设置python环境(v3.11)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 安装pip依赖(清华大学镜像源)
        working-directory: ./hexo-blog-aurora
        run: pip install -r requirements.txt

      - name: 安装pip依赖(清华大学镜像源) - main
        working-directory: ./hexo-blog
        run: pip install -r requirements.txt

      # - name: 自动配置博客图片,图片转webp
      #   run: |
      #     python handle_img.py

      # - name: 更新hexo-blog项目
      #   uses: Smart-Transportation/push@v1.3
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     branch: 'main'
      #     author_email: 'github-actions[bot]@users.noreply.github.com'
      #     author_name: 'github-actions[bot]'
      #     message: '🐳 chore: 更新hexo-blog文档图片'
      #     repository: nichuanfang/blog

      # 处理main分支的文档和图片
      - name: transform 'main' branch
        working-directory: ./hexo-blog
        env:
          THEME: ${{ vars.THEME }}
        run: |
          python transform.py $THEME

      - name: 安装npm依赖
        working-directory: ./hexo-blog-aurora
        run: npm install

      - name: npm构建
        working-directory: ./hexo-blog-aurora
        run: npm run build

      - name: 处理api文件
        working-directory: ./hexo-blog-aurora
        run: |
          python handle_api.py

      - name: 处理dist文件
        working-directory: ./hexo-blog-aurora
        run: |
          python handle_dist.py

      - name: 部署到github
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: nichuanfang/nichuanfang.github.io
          publish_branch: gh-pages # default: gh-pages
          publish_dir: ./hexo-blog-aurora/public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: 发布blog服务
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: 'ssh scp ssh pipelines'
          LASTSSH: 'Doing something after copying'
        continue-on-error: true
        with:
          # HC代表发布xray配置的服务器
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          pass: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          connect_timeout: 20s
          first_ssh: |
            systemctl stop nginx
            rm -rf /root/blog
          scp: |
            './hexo-blog-aurora/public/*' => /root/blog
          last_ssh: |
            chmod 777 /root/blog
            systemctl start nginx

  fluid:
    runs-on: ubuntu-latest
    if: ${{ vars.THEME == 'fluid' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false
          path: hexo-blog

      - uses: actions/checkout@v4
        with:
          ref: fluid-theme
          fetch-depth: 0
          persist-credentials: false
          path: hexo-blog-fluid

      - uses: actions/checkout@v4
        with:
          repository: nichuanfang/hexo-blog-vercel
          ref: main
          fetch-depth: 0
          persist-credentials: false
          path: hexo-blog-vercel

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18

      - name: Cache NPM dependencies
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: 设置python环境(v3.11)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 安装pip依赖(清华大学镜像源)- fluid
        working-directory: ./hexo-blog-fluid
        run: pip install -r requirements.txt

      - name: 安装pip依赖(清华大学镜像源) - main
        working-directory: ./hexo-blog
        run: pip install -r handler/requirements.txt

      - id: changed_files
        name: git-changesets
        continue-on-error: true
        uses: collin-miller/git-changesets@v1
        with:
          format: json

        # 处理main分支的文档和图片
      - name: transform 'main' branch
        working-directory: ./hexo-blog
        id: transform
        env:
          THEME: ${{ vars.THEME }}
          CHANGES_ADD: ${{ steps.changed_files.outputs.added }}
          CHANGES_MOD: ${{ steps.changed_files.outputs.modified }}
        run: |
          python handler/transform.py $THEME $CHANGES_ADD $CHANGES_MOD

      - name: 安装npm依赖
        working-directory: ./hexo-blog-fluid
        run: npm install

      - name: npm构建
        working-directory: ./hexo-blog-fluid
        run: npm run build

      - name: 处理dist文件
        working-directory: ./hexo-blog-fluid
        run: |
          python handle.py
          rm -rf ../hexo-blog-vercel/*
          cp -rf vercel.json ../hexo-blog-vercel
          cp -rf ./public/* ../hexo-blog-vercel

      # 更新hexo-blog项目
      - name: 更新hexo-blog项目
        uses: Smart-Transportation/push@v1.3
        with:
          directory: ./hexo-blog-fluid
          github_token: ${{ secrets.GH_TOKEN }}
          branch: 'fluid-theme'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          author_name: 'github-actions[bot]'
          message: '🐳 chore: 更新hexo-blog-fluid主题文件'
          repository: nichuanfang/blog

      - name: 部署到github
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: nichuanfang/nichuanfang.github.io
          publish_branch: gh-pages # default: gh-pages
          publish_dir: ./hexo-blog-fluid/public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: 发布到vercel仓库
        uses: Smart-Transportation/push@v1.3
        with:
          directory: ./hexo-blog-vercel
          github_token: ${{ secrets.GH_TOKEN }}
          branch: 'main'
          author_email: 'f18326186224@gmail.com'
          author_name: 'nichuanfang'
          message: '🐳 chore: 更新vercel仓库'
          repository: nichuanfang/hexo-blog-vercel

      # 更新hexo-blog文章图片
      - name: 更新hexo-blog文章图片
        #如果不需要更新图片，可以注释掉这一步 通过transform的输出变量should_post_update判断
        if: ${{ steps.transform.outputs.should_post_update == 'true' }}
        uses: Smart-Transportation/push@v1.3
        with:
          directory: ./hexo-blog
          github_token: ${{ secrets.GH_TOKEN }}
          branch: 'main'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          author_name: 'github-actions[bot]'
          message: '🐳 chore: 更新blog文章图片'
          repository: nichuanfang/blog
